---

image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

stages:
  - build
  - push

services:
- name: $RUNNER_IMAGE
  alias: docker

Build docker image:
  stage: build
  before_script: &before_script
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - cp $PRIVATE_KEY git.priv
    - docker build --build-arg PRIVATE_TOKEN="$PRIVATE_TOKEN" --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - admin

Push image:
  stage: push
  before_script: *before_script
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - admin
