---

image: docker:stable
variables:
  DOCKER_DRIVER: overlay2
  PRIVATE_KEY: $PRIVATE_KEY
stages:
  - build
  - push

services:
- $RUNNER_IMAGE

Build docker image:
  stage: build
  before_script: &before_script
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --build-arg PRIVATE_KEY="$PRIVATE_KEY" --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  tags:
    - admin

#--build-arg PRIVATE_CERT=$PRIVATE_KEY 
Push image:
  stage: push
  before_script: *before_script
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  tags:
    - admin
